# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - /app/vendor
      - /app/var
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      # APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###